feat: created data/Order
Effect-TS/schema pull request #136
Opened 2023-03-06 19:24 UTC by jessekelly881

Create data/Order and refactor filters, transforms to use it

2023-03-07 15:26 UTC, mikearnaldi commented
I think `sort` would violate `encoded = encode(decode(encoded))` cc @gcanti

2023-03-07 15:29 UTC, jessekelly881 commented
Yeah, it would. Is this a hard restriction? If so, I think quite a few transformations break this rule. E.g. String/trim

2023-03-07 19:51 UTC, mikearnaldi commented
I am not a fan of imposing the laws on everything, I was just kind of noticing. We could maybe mention it in the docs

2023-03-11 14:42 UTC, jessekelly881 commented
Maybe it makes sense to have two types of transformations. An invariant(two way) version and a covariant(one way) version.

2023-03-11 14:45 UTC, mikearnaldi commented
Would be problematic for the design of schema to support something like
that. In its heart schema is bidirectional but I don't think we should make
it a law that encoded values should match inputs, as long ad decoding again
will lead to the same decoded type

On Sat, 11 Mar 2023, 14:42 Jesse Kelly, ***@***.***> wrote:

> Maybe it makes sense to have two types of transformations. An
> invariant(two way) version and a covariant(one way) version.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Effect-TS/schema/pull/136#issuecomment-1464925976>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFZAKCROLQNAJ4JBN4L4UU3W3SFNNANCNFSM6AAAAAAVRRABXU>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-03-11 14:48 UTC, jessekelly881 commented
Makes sense. I think sort is probably "close enough" to work whereas filtering for unique values seems to heavy handed. But what do you think?

2023-03-11 14:49 UTC, mikearnaldi commented
Well that should be fine too, you're filtering out always according to the
same filters

On Sat, 11 Mar 2023, 14:48 Jesse Kelly, ***@***.***> wrote:

> Makes sense. I think sort is probably "close enough" to work whereas
> filtering for unique values seems to heavy handed. But what do you think?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Effect-TS/schema/pull/136#issuecomment-1464927183>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFZAKCTQMBWH7HANRDXBKXLW3SGEPANCNFSM6AAAAAAVRRABXU>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-03-16 20:36 UTC, jessekelly881 commented
@mikearnaldi Makes sense. Btw, I added docs and I also reduced the scope of the pr to just include the sort and uniq filters.

2023-03-17 12:25 UTC, gcanti requested changes

2023-03-17 12:25 UTC, gcanti commented on README.md
> +const schema = pipe(S.array(S.number), S.sort(N.Order));
typo: `sort` -> `uniq`

2023-03-17 12:31 UTC, jessekelly881 commented on src/Schema.ts
> +      self,
How do you recommend we handle it in this case? Should we add isSorted and isUniq filters similar to trim and trimmed?

2023-03-17 13:15 UTC, gcanti commented on src/Schema.ts
> +      self,
yeah I would add `sorted` and `unique` filters

2023-03-17 13:30 UTC, jessekelly881 commented on src/Schema.ts
> +      (s) => RA.sortBy(...ords)(s)
How do you mean? , `RA.sortBy(...ords)` instead of `(s) => RA.sortBy(...ords)(s)`?

2023-03-17 13:44 UTC, gcanti commented on src/Schema.ts
> +      (s) => RA.sortBy(...ords)(s)
> RA.sortBy(...ords) instead of (s) => RA.sortBy(...ords)(s)?

^ this would be better, but I'm referring to the `ba` argument of `transform`:

```ts
export const sort = <A>(...ords: ReadonlyArray<Order.Order<A>>) =>
  (self: Schema<ReadonlyArray<A>>): Schema<ReadonlyArray<A>> =>
    transform(
      self,
      self, // TODO: sorted filter
      RA.sortBy(...ords), // simplify
      identity // this is just the identity function from "@effect/data/Function"
    )
```

2023-03-17 14:21 UTC, jessekelly881 commented on src/Schema.ts
> +      (s) => RA.sortBy(...ords)(s)
Oh I see. Ok

2023-05-17 21:13 UTC, closed without merging