feat: added S.required combinator
Effect-TS/schema pull request #173
Opened 2023-03-22 14:09 UTC by jessekelly881

Adds S.required

```js
const schema = S.required(S.struct({ a: S.optional(S.number) }))

expectParseSuccess(schema, { a: 1 }, { a: 1 })
expectParseFailure(schema, {}, "/a is missing")
```

https://github.com/colinhacks/zod#required

2023-03-27 17:47 UTC, gcanti requested changes

2023-03-27 17:47 UTC, gcanti commented on README.md
> +// $ExpectType Schema<Required<{ readonly a: string; readonly b: number; }>>
typo, should be `Schema<Required<{ readonly a?: string; readonly b?: number; }>>`

2023-03-27 17:47 UTC, gcanti commented on src/AST.ts
> +          O.map((rest) => [createUnion(rest)])
is this right?

in

```ts
type A = readonly [string, ...Array<number>, boolean]
type B = Required<A>
```

`B` is

```ts
type B = readonly [string, ...(number | boolean)[], number | boolean]
```

not 

```ts
type B = readonly [string, ...(number | boolean)[]]
```

2023-03-27 17:47 UTC, gcanti commented on src/AST.ts
> +    case "Refinement":
I'm not sure we can actually handle refinements or transformations, in `partial` I'm throwing at the moment

2023-03-27 18:21 UTC, jessekelly881 commented on README.md
> +// $ExpectType Schema<Required<{ readonly a: string; readonly b: number; }>>
Fixed

2023-03-27 18:43 UTC, jessekelly881 commented on src/AST.ts
> +          O.map((rest) => [createUnion(rest)])
Oh good catch. Let me see if I can fix it.

2023-03-27 19:39 UTC, jessekelly881 commented on src/AST.ts
> +          O.map((rest) => [createUnion(rest)])
The required type on tuples is odd.. For example,

```js
type A = readonly ["1", ...Array<"2">, "3", ...Array<"4">];
type B = Required<A>;

const b: B = ["1"]; // type checks correctly
```

2023-03-27 20:08 UTC, jessekelly881 commented on src/AST.ts
> +    case "Refinement":
Hmm. These tests are passing for me: 

```js
  it("required/ filter", () => {
    const schema = S.required(S.struct({
      a: S.optional(pipe(S.number, S.greaterThan(0)))
    }))

    expectParseSuccess(schema, { a: 1 }, { a: 1 })
    expectParseFailure(schema, {}, "/a is missing")
  })

  it("partial/ filter", () => {
    const schema = S.partial(S.struct({
      a: S.optional(pipe(S.number, S.greaterThan(0)))
    }))

    expectParseSuccess(schema, { a: 1 }, { a: 1 })
    expectParseSuccess(schema, {}, {})
  })
```

2023-03-27 22:44 UTC, jessekelly881 commented on src/AST.ts
> +          O.map((rest) => [createUnion(rest)])
Typescript is perfectly happy to have a rest element after a rest element, as strange as it behaves.. but schema isn't.

2023-03-27 23:08 UTC, jessekelly881 commented on src/AST.ts
> +          O.map((rest) => [createUnion(rest)])
That said, I think I've fixed it.

2023-03-28 08:47 UTC, gcanti commented on src/AST.ts
> +    case "Refinement":
ok merging, I'll check out later, thanks

2023-03-28 08:47 UTC, merged