Add combinator that splits a string into an array of strings
Effect-TS/schema pull request #359
Opened 2023-07-25 17:45 UTC by vecerek

Partially addresses #352 as a response to the received feedback in #353.

The idea is that once we can split strings into arrays of strings, we could implement another combinator that allows transforming arrays of type I into arrays of type A. With those two combinators: `split`, and `itemsAs` (for a lack of a better term for now), we could implement the same as the proposed `arrayFromDelimitedString` by chaining those combinators like so:

```ts
S.string.pipe(S.split(","), S.itemsAs(S.NumberFromString))
```

2023-07-25 20:40 UTC, vecerek commented
Once this PR gets accepted and merged, I have another one (depending on this one) lined up for a review: https://github.com/vecerek/schema/pull/1 😄

2023-07-26 05:29 UTC, gcanti requested changes

2023-07-26 05:29 UTC, gcanti commented on src/Schema.ts
> +export const split = (
Yes, a dual `split` API would be nice

2023-07-26 05:38 UTC, vecerek commented on src/Schema.ts
> +export const split = (
> should this be a [dual API](https://www.effect.website/docs/comparison/fp-ts#dual-apis)

The link shows 404 to me.

> Yes, a dual split API would be nice

@gcanti could you point me to a combinator that is implemented that way? I was mostly following the example of `trim` when working on this feature.

2023-07-26 05:41 UTC, vecerek commented on src/Schema.ts
> +export const split = (
nvm, I've found `extend`. I'll follow that one 🙂

2023-07-26 05:49 UTC, gcanti commented
> we could implement another combinator that allows transforming arrays of type I into arrays of type A

@vecerek this is `array` actually

```ts
const array: <I, A>(item: Schema<I, A>) => Schema<readonly I[], readonly A[]>
```

The missing piece seems a `compose` combinator:

```ts
export const compose: {
  <B, C>(bc: Schema<B, C>): <A>(ab: Schema<A, B>) => Schema<A, C>
  <A, B, C>(ab: Schema<A, B>, bc: Schema<B, C>): Schema<A, C>
} = dual(
  2,
  <A, B, C>(ab: Schema<A, B>, bc: Schema<B, C>): Schema<A, C> =>
    transform(ab, bc, identity, identity)
)
```

and then 

```ts
S.string.pipe(S.split(","), S.compose(S.array(S.NumberFromString)))
```

2023-07-26 05:53 UTC, vecerek commented
@gcanti the compose combinator sounds great! I think I've actually expressed interest in it before and didn't make this connection. Would you like me to change this PR implementing compose instead?

2023-07-26 05:54 UTC, vecerek commented on src/Schema.ts
> +export const split = (
Addressed in https://github.com/Effect-TS/schema/commit/881970a681e46c778f9f08e8e321046d4259e69a.

2023-07-26 05:55 UTC, gcanti commented
> Would you like me to change https://github.com/vecerek/schema/pull/1 implementing compose instead?

👍

2023-07-26 05:55 UTC, vecerek commented on src/Schema.ts
> +export const split = (
In the readme, do you prefer data-first or data-last code examples? Or should both be demonstrated?

2023-07-26 05:56 UTC, gcanti approved these changes

2023-07-26 06:14 UTC, gcanti commented on src/Schema.ts
> +export const split = (
data-last is fine, thanks

2023-07-26 06:14 UTC, merged

2023-07-26 06:37 UTC, vecerek commented
@gcanti I couldn't change the base of my previous PR, so I was forced to open a new one: https://github.com/Effect-TS/schema/pull/361.